### ISSUE TITLE
Уровень не завершается.

### ISSUE THREAD

**Issue by Dragote** [LoinASD/Sudoku#1]
При полном заполнении всех полей цифрами уровень не завершается.
![image](https://user-images.githubusercontent.com/31729910/40560575-a526610e-6084-11e8-9921-db9a0b2d55cd.png)

**Comment by Onotolo** [comment]
Solved in [https://github.com/LoinASD/Sudoku/commit/265422907ff7003110ac247d37d13984e62a7597](url)
