### ISSUE TITLE
Неровное размещение поля.

### ISSUE THREAD

**Issue by Dragote** [LoinASD/Sudoku#2]
На любом устройстве таблица с цифрами находится не ровно по центру. 
![image](https://user-images.githubusercontent.com/31729910/40560748-2926217e-6085-11e8-98c0-e629bd966acd.png)

**Comment by Onotolo** [comment]
Solved in [https://github.com/LoinASD/Sudoku/commit/265422907ff7003110ac247d37d13984e62a7597](url)
